apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/tiagoaramos/deploy-applications.git
      revision: HEAD
      directories:
      - path: applications/*
      - path: applications/*/**
        exclude: true
  template:
      metadata:
          name: '{{.path.basename}}'
      spec:
          project: default
          source:
              repoURL: https://github.com/tiagoaramos/deploy-applications.git
              path: '{{.path.path}}/{{.path.basename}}-helm'
              targetRevision: HEAD
              helm:
                  valueFiles:
                      - values.yaml
          destination:
              server: 'https://kubernetes.default.svc'
              namespace: '{{.path.basename}}'
          syncPolicy:
              syncOptions:
              - CreateNamespace=true
