# PersistentVolumeClaim para Drone CI
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-data-pvc
  namespace: drone-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
---
# PersistentVolumeClaim para logs do Drone
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-logs-pvc
  namespace: drone-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
---
# PersistentVolume para Drone Data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-data-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /var/cluster_data/drone/data
---
# PersistentVolume para Drone Logs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /var/cluster_data/drone/logs
---
# StorageClass para volumes locais
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
