apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-config
  namespace: drone-space
data:
  daemon.json: |
    {
      "insecure-registries": [],
      "registry-mirrors": [],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "3"
      }
    }
