# PersistentVolumeClaim para Drone CI
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-data-pvc
  namespace: drone-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
---
# PersistentVolumeClaim para logs do Drone
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-logs-pvc
  namespace: drone-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage