apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ca-cert
  namespace: drone-space
data:
  harbor-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIRAO8yYmQ25tjcVzLLPnY8oeAwDQYJKoZIhvcNAQELBQAw
    FDESMBAGA1UEAxMJaGFyYm9yLWNhMB4XDTI1MDkyOTIwMDAzMloXDTI2MDkyOTIw
    MDAzMlowFDESMBAGA1UEAxMJaGFyYm9yLWNhMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEArFVy1M/4HBG7eWwSkq389FtMWokBCrbdGMy1c1s2hmq5ldA3
    +gSQAKQFKOSBZLP3RD5hGe6SQvFaPz9v7O/qlpAUd4D8jE/zT12HDlm86meW3OPt
    ZxiHMBR3xI+Nrvur0+00ehK1CWifEBEAHbDuUIiG6/VI/19kjmGrcmyOVM5Ck+A0
    t3o061G5oa1D7gwRvo2ZrlFsjgVEkhnIBUcwCOxRsw7rg+j5g+bxZ7sVdlFsgzdw
    scPjEnIS9tzLGBrvaT1ZinvD/9koyHyYlHk4LmYzKucRBcv8fOLSagbbNG9eLX9U
    XYRf64q//czH+1YmH7ObpgkhA564CATes+zUjQIDAQABo2EwXzAOBgNVHQ8BAf8E
    BAMCAqQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFGnFeAUehkSurfsjR5yPJ3j8Lg5aMA0GCSqGSIb3DQEB
    CwUAA4IBAQCGbP8qn7SVbAE6XNTf8A3L8uPS4/7L7n8CxioVCV+f730og4uEsLNu
    KjHPc6Z9N9Gy5V8a7/xqprLOPrZnw6AbzXYW49Jtfv7tl8LZ/RCYT6n5Hom7tvYl
    O1sjsNIiAvgyD8tWYfXEgV4Wo6VlBI5NADgfHC6MQb/zTJhDHYmqoZfHBpvSIRXn
    6cEg+YGWNfM9In28fnWNX6qwXMGvCHyScLe9Z0z0zkk7z/TOMvJBwQCJwPcyZaxM
    VdFmBLYxRQwDAJ44BmPmzaUuTRgiW5TNiKRUffzUQFftf+EQYArF6MbpGhTs+gPy
    TfWUBWCuCnmGfdan7/Dn4zzMnJPm237C
    -----END CERTIFICATE-----
