# PersistentVolumeClaims para ArgoCD
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-redis-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
# PersistentVolumeClaim para ArgoCD Server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-server-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
# PersistentVolumeClaim para ArgoCD Repo Server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-repo-server-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage