apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: site
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: site-space
  project: default
  source:
    repoURL: 'https://github.com/tiagoaramos/deploy-applications.git'
    path: applications/site/site-helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
